### ISSUE TITLE
PD 3.1 (PD130)

### ISSUE THREAD

**Issue by harrypm** [mikepdiy/thinkpad-mod#4]
So I've got W530 which has a 3940xm CPU, so it rejects anything that's under 135w in terms of powering laptop while charging but needs 170w with the 1.5kohm resistance on the signal to ground pin to actually run without being throttled by the power IC.

Now PD 3.1 has the 130w spec, I have a little pile of power banks and car adaptors etc which have this spec and slightly beyond it for some of the newer laptop bricks.

What I am wondering is can you make adapters with that appropriate configuration to leverage PD 3.1?

If so I would like to buy one most likely!

**Comment by mikepdiy** [comment]
The new PD standard specs do indeed go over 100W but that comes at voltages above 20. In order to make a mod that would not damage the laptops the voltage needs to lowered and a few other precautions have to be taken. The resulted mod would not fit in the case of a w530 sadly. I have not developed anything since the standard specs have been upgraded just because of this issue. Sadly for you the only option would be to use an external adapter to your laptop between a type-c cable and a PD charger; this way you would get the desired wattage.

**Comment by harrypm** [comment]
Thanks for responding.
